trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: productName
    displayName: Product Name
    type: string

  - name: barewindowsVM
    displayName: Deploy Bare Windows VM
    type: boolean
    default: false

  - name: appName
    displayName: Provide App Name with Tag
    type: string

  - name: DryRun
    displayName: Dry Run Mode
    type: boolean
    default: false

stages:
  - stage: Provision_Dev_Env
    displayName: Provision Dev Env
    dependsOn: []
    jobs:
      - template: infra-job-template.yml
        parameters:
          SubscriptionName: '<service_connection>'
          Backend: ${{ parameters.productName }}
          DryRun: ${{ parameters.DryRun }}
          barewindowsVM: ${{ parameters.barewindowsVM }}
          appName: ${{ parameters.appName }}
          productName: ${{ parameters.productName }}
