trigger:
  branches:
    include:
      - main
  paths:
    include:
      - apps/*/Dockerfile   # triggers if Dockerfile changes in any app folder

parameters:
  - name: appName
    displayName: "Application Name"
    type: string

variables:
  # Update with  ACR service connection name from Azure DevOps)
  ACR_NAME: "myacrregistry"
  IMAGE_TAG: "$(Build.BuildId)"

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: DockerBuildPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Log in to ACR
          - task: Docker@2
            displayName: "Login to ACR"
            inputs:
              command: login
              containerRegistry: "$(ACR_NAME)"

          # Build and Push image
          - task: Docker@2
            displayName: "Build and Push Docker Image"
            inputs:
              command: buildAndPush
              repository: "$(parameters.appName)"
              dockerfile: "**/Dockerfile"
              containerRegistry: "$(ACR_NAME)"
              tags: |
                $(IMAGE_TAG)
